env:
  global:
    - secure: ZErwEGNao3SD9q3M1m1/MOPuYJ0Ihd7JoULM0fgg8OkdFAwm0GCWTsdyhETqfLjnNmsyIc0YR/s4/LxZVRHpnsfg1osYQ1S96E2oSj9swWOBJaUF9dqVrL3oQ6d3APTzoDMICIlDJoLfEaUJ9vy6Mm3whOAu3Xj0jCsZk9vdQ2o=
before_install:
  - sudo add-apt-repository --yes ppa:hansjorg/rust
  - sudo add-apt-repository --yes ppa:cmrx64/cargo
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq rust-nightly cargo
script:
  - cargo build -v
  - make test
  - cargo doc --no-deps -v
  - mv target/doc doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
